import React from 'react';
import './style.css';

export default function App() {
  const data = [
    {
      'Key Translation': 'TotalMember',
      English: 'Total member',
      'Chinese Simplified': '会员总数',
      'Chinese Traditional': '會員總數',
      Hindi: 'कुल सदस्य ',
      Japan: '会員総数',
      Korean: '총 회원 수',
      Malay: 'Jumlah ahli',
      Thai: 'สมาชิกทั้งหมด',
      Vietnamese: 'Tổng số thành viên',
    },
    {
      'Key Translation': 'TotalWalletBalance',
      English: 'Total wallet balance',
      'Chinese Simplified': '钱包总余额',
      'Chinese Traditional': '錢包總餘額',
      Hindi: 'कुल वॉलेट राशि ',
      Japan: '財布の残高の合計',
      Korean: '총 지갑 잔액',
      Malay: 'Jumlah baki dompet',
      Thai: 'ยอดคงเหลือในกระเป๋าเงินทั้งหมด',
      Vietnamese: 'Tổng số dư ví',
    },
    {
      'Key Translation': 'TotalSupervisor',
      English: 'Total Supervisor',
      'Chinese Simplified': '主任总数',
      'Chinese Traditional': '主任總數',
      Hindi: 'कुल सुपरवाइजर ',
      Japan: 'スーパーバイザー合計',
      Korean: '총 감독자',
      Malay: 'Jumlah Penyelia',
      Thai: 'หัวหน้างานทั้งหมด',
      Vietnamese: 'Tổng số giám sát',
    },
    {
      'Key Translation': 'TotalManager',
      English: 'Total Manager',
      'Chinese Simplified': '经理总数',
      'Chinese Traditional': '經理總數',
      Hindi: 'कुल प्रबंधक ',
      Japan: '合計 マネージャー',
      Korean: '총 관리자',
      Malay: 'Jumlah Pengurus ',
      Thai: 'ผู้จัดการทั้งหมด',
      Vietnamese: 'Tổng số quản lý',
    },
    {
      'Key Translation': 'TotalMarketingManager',
      English: 'Total Marketing Manager',
      'Chinese Simplified': '市场经理总数',
      'Chinese Traditional': '市場經理總數',
      Hindi: 'कुल मार्केटिंग प्रबंधक',
      Japan: '合計 マーケティング・マネジャー',
      Korean: '총 마케팅 관리자',
      Malay: 'Jumlah Pengurus Pemasaran',
      Thai: 'ผู้จัดการฝ่ายการตลาดทั้งหมด',
      Vietnamese: 'Tổng số quản lý tiếp thị',
    },
    {
      'Key Translation': 'TotalRegionalManager',
      English: 'Total Regional Manager',
      'Chinese Simplified': '区域经理总数',
      'Chinese Traditional': '區域經理總數',
      Hindi: 'कुल क्षेत्रीय प्रबंधक',
      Japan: '合計 地域マネージャー',
      Korean: '총 지역 관리자',
      Malay: 'Jumlah Pengurus Wilayah',
      Thai: 'ผู้จัดการระดับภูมิภาคทั้งหมด',
      Vietnamese: 'Tổng số quản lý vùng',
    },
    {
      'Key Translation': 'TotalDirector',
      English: 'Total Director',
      'Chinese Simplified': '总监总数',
      'Chinese Traditional': '總監總數',
      Hindi: 'कुल निदेशक ',
      Japan: '合計 ディレクター',
      Korean: '총 이사',
      Malay: 'Jumlah Pengarah',
      Thai: 'ผู้อำนวยการทั้งหมด',
      Vietnamese: 'Tổng số giám đốc',
    },
    {
      'Key Translation': 'TotalGlobalDirector',
      English: 'Total Global Director',
      'Chinese Simplified': '国际总监总数',
      'Chinese Traditional': '國際總監總數',
      Hindi: 'कुल वैश्विक निदेशक ',
      Japan: 'グローバルディレクター',
      Korean: '총 글로벌 이사',
      Malay: 'Jumlah Pengarah Global ',
      Thai: 'ผู้อำนวยการระดับโลกทั้งหมด',
      Vietnamese: 'Tổng số giám đốc toàn cầu',
    },
    {
      'Key Translation': 'TotalGroupInvestment',
      English: 'Total Group Investment',
      'Chinese Simplified': '团队托管总额',
      'Chinese Traditional': '團隊託管總額',
      Hindi: 'को पंजीकृत किया गया ',
      Japan: 'グループ投資総額',
      Korean: '총 그룹 투자',
      Malay: 'Jumlah Pelaburan Kumpulan',
      Thai: 'การลงทุนของกลุ่มทั้งหมด',
      Vietnamese: 'Tổng đầu tư nhóm',
    },
    {
      'Key Translation': 'RegisteredOnDate',
      English: 'Registered on {{date}}',
      'Chinese Simplified': '注册于 ',
      'Chinese Traditional': '註冊於',
      Hindi: 'प्राप्ति की तिथि ',
      Japan: '登記簿謄本 ',
      Korean: '등록 날짜',
      Malay: 'Didaftarkan pada {{tarikh}}',
      Thai: 'ลงทะเบียนเมื่อ ',
      Vietnamese: 'Đăng ký vào',
    },
    {
      'Key Translation': 'UpdatedOnDate',
      English: 'Updated on {{date}}',
      'Chinese Simplified': '更新于 ',
      'Chinese Traditional': '更新於 ',
      Hindi: 'को अपडेट किया गया ',
      Japan: 'アップデート日 ',
      Korean: '업데이트 날짜',
      Malay: 'Dikemas kini pada {{tarikh}}',
      Thai: 'อัปเดตเมื่อ ',
      Vietnamese: 'Cập nhật lúc',
    },
    {
      'Key Translation': 'AchievedDate',
      English: 'Achieved Date',
      'Chinese Simplified': '达标日期',
      'Chinese Traditional': '達標日期',
      Hindi: 'प्रायोजक की संख्या ',
      Japan: '登録完了日',
      Korean: '달성 날짜',
      Malay: 'Tarikh Dicapai',
      Thai: 'วันที่ได้รับ',
      Vietnamese: 'Ngày nhận',
    },
    {
      'Key Translation': 'Fulfilled',
      English: 'Fulfilled',
      'Chinese Simplified': '完成',
      'Chinese Traditional': '完成',
      Hindi: 'पूरा किया गया ',
      Japan: '完了',
      Korean: '완료',
      Malay: 'Dipenuhi',
      Thai: 'เติมเต็มแล้ว',
      Vietnamese: 'ĐÃ HOÀN THÀNH',
    },
    {
      'Key Translation': 'DirectReferral',
      English: 'Direct Referral',
      'Chinese Simplified': '直推人数',
      'Chinese Traditional': '直推人數',
      Hindi: 'डायरेक्ट रेफरल ',
      Japan: 'ダイレクト・リファラル',
      Korean: '직접 추천',
      Malay: 'Rujukan Terus',
      Thai: 'การแนะนำโดยตรง',
      Vietnamese: 'Giới thiệu trực tiếp',
    },
    {
      'Key Translation': 'UnableToConnectToServer',
      English:
        'Unable to connect to server. Please check your network connection and try again.',
      'Chinese Simplified': '无法连接到服务器。 请检查您的网络连接并重试。',
      'Chinese Traditional': '無法連接到服務器。請檢查您的網絡連接並重試。',
      Malay:
        'Jaringan tidak dapat dicapai. Sila semak sambungan rangkaian anda dan cuba lagi.',
    },
    {
      'Key Translation': 'UnexpectedErrorOccurredWhileProcessingYourRequest',
      English:
        'Unexpected error occurred while processing your request. Please try again later.',
      'Chinese Simplified': '处理您的请求时出现意外错误。 请稍后再试。',
      'Chinese Traditional': '處理您的請求時出現意外錯誤。請稍後再試。',
      Malay:
        'Ralat yang tidak dijangka berlaku semasa memproses permintaan anda. Sila cuba sebentar lagi.',
    },
    {
      'Key Translation': 'MarketNews',
      English: 'Market News',
      'Chinese Simplified': '市场新闻',
      'Chinese Traditional': '市場新聞',
      Hindi: 'बाज़ार से जुड़े समाचार ',
      Japan: 'マーケットニュース',
      Korean: '시장 뉴스',
      Malay: 'Berita Pasaran',
      Thai: 'ข่าวการตลาด',
      Vietnamese: 'Tin thị trường',
    },
    {
      'Key Translation': 'PressRelease',
      English: 'Press Release',
      'Chinese Simplified': '新闻稿',
      'Chinese Traditional': '新聞稿',
      Hindi: 'प्रेस विज्ञप्ति ',
      Japan: 'プレスリリース',
      Korean: '보도 자료',
      Malay: 'Siaran Akhbar',
      Thai: 'ข่าวประชาสัมพันธ์',
      Vietnamese: 'Thông cáo báo chí',
    },
    {
      'Key Translation': 'Media&Gallery',
      English: 'Media & Gallery',
      'Chinese Simplified': '媒体&画廊',
      'Chinese Traditional': '媒體及畫廊',
      Hindi: 'मीडिया और गैलरी ',
      Japan: 'メディアとギャラリー',
      Korean: '미디어 & 갤러리',
      Malay: 'Media & Galeri',
      Thai: 'สื่อและแกลเลอรี่',
      Vietnamese: 'Phương tiện & Thư viện',
    },
    {
      'Key Translation': 'Photo',
      English: 'Photo',
      'Chinese Simplified': '相片',
      'Chinese Traditional': '相片',
      Hindi: 'फोटो ',
      Japan: '写真',
      Korean: '사진',
      Malay: 'Foto',
      Thai: 'รูปถ่าย',
      Vietnamese: 'Ảnh',
    },
    {
      'Key Translation': 'EventAlbum',
      English: 'Event Album',
      'Chinese Simplified': '活动相册',
      'Chinese Traditional': '活動相冊',
      Hindi: 'कार्यक्रम एल्बम ',
      Japan: 'イベントアルバム',
      Korean: '이벤트 앨범',
      Malay: 'Album Acara',
      Thai: 'อัลบั้มกิจกรรม',
      Vietnamese: 'Album sự kiện',
    },
    {
      'Key Translation': 'Video',
      English: 'Video',
      'Chinese Simplified': '视频',
      'Chinese Traditional': '視頻',
      Hindi: 'वीडियो ',
      Japan: '動画',
      Korean: '비디오',
      Malay: 'Video',
      Thai: 'วิดีโอ',
      Vietnamese: 'Video',
    },
    {
      'Key Translation': 'StayTunedForUpdate',
      English: 'Stay tuned for update',
      'Chinese Simplified': '敬请期待更新',
      'Chinese Traditional': '敬請期待更新',
      Hindi: 'अपडेट के लिए बने रहें ',
      Japan: '最新情報をお届けします',
      Korean: '업데이트를 계속 지켜봐 주세요',
      Malay: 'Nantikan kemas kini',
      Thai: 'คอยติดตามการอัปเดต',
      Vietnamese: 'Nhớ theo dõi các cập nhật mới',
    },
    {
      'Key Translation': 'ThereIsAlackOfNotableNews',
      English:
        'There is a lack of notable news or updates to share as of the present moment',
      'Chinese Simplified': '目前还没有值得关注的新闻或更新可以分享',
      'Chinese Traditional': '目前還沒有值得關注的新聞或更新可以分享',
      Japan: '現在、特筆すべきニュースやアップデートはありません。',
      Korean: '현재 공유 또는 주목할 만한 소식이나 업데이트가 없습니다.',
      Malay:
        'Terdapat kekurangan berita penting atau kemas kini untuk dikongsi pada masa ini',
      Thai: 'ยังขาดข่าวสารหรือการอัปเดตที่น่าสนใจที่จะนำมาแบ่งปัน ณ ปัจจุบัน',
      Vietnamese: 'Hiện không có tin tức hay cập nhật nổi bật để chia sẻ',
    },
    {
      'Key Translation': 'Prev',
      English: 'Prev',
      'Chinese Simplified': '上一个',
      'Chinese Traditional': '上一個',
      Malay: 'Sebelum',
    },
    {
      'Key Translation': 'SelectAlbumName',
      English: 'Select Album Name',
      'Chinese Simplified': '选择相册名称',
      'Chinese Traditional': '選擇相冊名稱',
      Hindi: 'एल्बम के नाम का चयन करें ',
      Japan: 'アルバム名を選択',
      Korean: '앨범명 선택',
      Malay: 'Pilih Nama Album',
      Thai: 'เลือกชื่ออัลบั้ม',
      Vietnamese: 'Chọn tên album',
    },
    {
      'Key Translation': 'VideoGallery',
      English: 'Video Gallery',
      'Chinese Simplified': '视频库',
      'Chinese Traditional': '視頻庫',
      Hindi: 'वीडियो गैलरी ',
      Japan: '動画ギャラリー',
      Korean: '비디오 갤러리',
      Malay: 'Galeri Video',
      Thai: 'แกลเลอรี่วิดีโอ',
      Vietnamese: 'Thư viện video',
    },
    {
      'Key Translation': 'VideoGalleryDetails',
      English: 'Video Gallery Details',
      'Chinese Simplified': '视频库详细信息',
      'Chinese Traditional': '視頻庫詳細信息',
      Malay: 'Butiran Galeri Video',
    },
    {
      'Key Translation': 'SelectVideoName',
      English: 'Select Video Name',
      'Chinese Simplified': '选择视频名称',
      'Chinese Traditional': '選擇視頻名稱',
      Hindi: 'वीडियो के नाम का चयन करें ',
      Japan: '動画名を選択',
      Korean: '동영상명 선택',
      Malay: 'Pilih Nama Video',
      Thai: 'เลือกชื่อวิดีโอ',
      Vietnamese: 'Chọn tên video',
    },
    {
      'Key Translation': 'MT5Report',
      English: 'MT5 Report',
      'Chinese Simplified': 'MT5报告',
      'Chinese Traditional': 'MT5報告',
      Hindi: 'MT5 रिपोर्ट ',
      Japan: 'MT5レポート',
      Korean: 'MT5 보고서',
      Malay: 'Laporan MT5',
      Thai: 'รายงาน MT5',
      Vietnamese: 'Báo cáo MT5',
    },
    {
      'Key Translation': 'TradingAccountOverview',
      English: 'Trading Account Overview',
      'Chinese Simplified': '交易账户概述',
      'Chinese Traditional': '交易賬戶概述',
      Hindi: 'ट्रेडिंग खाते का अवलोकन',
      Japan: '口座概要',
      Korean: '트레이딩 계좌 개요',
      Malay: 'Gambaran Keseluruhan Akaun Dagangan',
      Thai: 'ภาพรวมของบัญชีเทรด',
      Vietnamese: 'Tổng quan tài khoản giao dịch',
    },
    {
      'Key Translation': 'WeeklyProfitReport',
      English: 'Weekly Profit Report',
      'Chinese Simplified': '每周利润报告',
      'Chinese Traditional': '每周利潤報告',
      Malay: 'Laporan Untung Mingguan',
    },
    {
      'Key Translation': 'Swap',
      English: 'Swap',
      'Chinese Simplified': '库存费',
      'Chinese Traditional': '庫存費',
      Hindi: 'स्वाप',
      Japan: 'スワップ',
      Korean: '스왑',
      Malay: 'Tukar',
      Thai: 'สลับ',
      Vietnamese: 'Đổi',
    },
    {
      'Key Translation': 'Profit',
      English: 'Profit',
      'Chinese Simplified': '利润',
      'Chinese Traditional': '利潤',
      Hindi: 'लाभ ',
      Japan: '利益',
      Korean: '이익',
      Malay: 'Untung',
      Thai: 'กำไร',
      Vietnamese: 'Lợi nhuận',
    },
    {
      'Key Translation': 'Time',
      English: 'Time',
      'Chinese Simplified': '时间',
      'Chinese Traditional': '時間',
      Hindi: 'समय ',
      Japan: '時間',
      Korean: '시간',
      Malay: 'Masa',
      Thai: 'เวลา',
      Vietnamese: 'Thời gian',
    },
    {
      'Key Translation': 'Position',
      English: 'Position',
      'Chinese Simplified': '仓位',
      'Chinese Traditional': '倉位',
      Hindi: 'स्थिति',
      Japan: 'ポジション',
      Korean: '포지션',
      Malay: 'kedudukan',
      Thai: 'ตำแหน่ง',
      Vietnamese: 'Vị thế',
    },
    {
      'Key Translation': 'Symbol',
      English: 'Symbol',
      'Chinese Simplified': '品种',
      'Chinese Traditional': '品種',
      Hindi: 'प्रतीक ',
      Japan: 'シンボル',
      Korean: '기호',
      Malay: 'Simbol',
      Thai: 'สัญลักษณ์',
      Vietnamese: 'Ký hiệu',
    },
    {
      'Key Translation': 'Volume',
      English: 'Volume',
      'Chinese Simplified': '成交量',
      'Chinese Traditional': '成交量',
      Hindi: 'आयतन',
      Japan: '数量',
      Korean: '거래량',
      Malay: 'Kelantangan',
      Thai: 'ปริมาณ',
      Vietnamese: 'Khối lượng',
    },
    {
      'Key Translation': 'Price',
      English: 'Price',
      'Chinese Simplified': '价格',
      'Chinese Traditional': '價格',
      Hindi: 'कीमत',
      Japan: '価格',
      Korean: '가격',
      Malay: 'harga',
      Thai: 'ราคา',
      Vietnamese: 'Giá',
    },
    {
      'Key Translation': 'S/L',
      English: 'S/L',
      'Chinese Simplified': '止损',
      'Chinese Traditional': '止損',
      Hindi: 'स्टॉप/लॉस ',
      Japan: 'S/L',
      Korean: '손절매',
      Malay: 'henti rugi',
      Thai: 'S/L',
      Vietnamese: 'S/L',
    },
    {
      'Key Translation': 'T/P',
      English: 'T/P',
      'Chinese Simplified': '止盈',
      'Chinese Traditional': '止盈',
      Hindi: 'टेक प्रॉफिट',
      Japan: 'T/P',
      Korean: '이익 실현',
      Malay: 'mengambil keuntungan',
      Thai: 'T/P',
      Vietnamese: 'T/P',
    },
    {
      'Key Translation': 'WithdrawAllTheMoneyInYourWallet',
      English: 'Withdraw all the money in your Income Wallet 1',
      'Chinese Simplified': '提取收入钱包中的所有资金 1',
      'Chinese Traditional': '提取收入錢包中的所有資金 1',
      Malay: 'Keluarkan semua wang dalam Dompet Pendapatan anda 1',
    },
    {
      'Key Translation': 'IncomeWallet1',
      English: 'Income wallet 1',
      'Chinese Simplified': '收入钱包 1',
      'Chinese Traditional': '收入錢包 1',
      Malay: 'Dompet pendapatan 1',
    },
    {
      'Key Translation': 'PackageTermination',
      English: 'Package termination',
      'Chinese Simplified': '终止配套',
      'Chinese Traditional': '終止配套',
      Malay: 'Penamatan pakej',
    },
    {
      'Key Translation': 'EnteringAITradingEra',
      English: 'Entering AI Trading Era',
      'Chinese Simplified': '进入AI交易时代',
      'Chinese Traditional': '進入AI交易時代',
      Malay: 'Memasuki Era Dagangan AI',
    },
    {
      'Key Translation': 'OurCoreTechnologyNEURONTradingSystem',
      English:
        'Our core technology NEURON Trading System can swiftly collect massive amount of current market information and historical trading data, filter and categorize the data within seconds, make accurate predictions, and select the most suitable trading strategy.',
      'Chinese Simplified':
        '我们的核心技术NEURON交易系统可以快速收集海量的当前市场信息和历史交易数据，在秒级内对数据进行筛选和分类，做出准确的预测，选择最合适的交易策略。',
      'Chinese Traditional':
        '我們的核心技術NEURON交易系統可以快速收集海量的當前市場信息和歷史交易數據，在秒級內對數據進行篩选和分類，做出準確的預測，選擇最合適的交易策略。',
      Malay:
        'Teknologi teras kami Sistem Perdagangan NEURON boleh dengan pantas mengumpul sejumlah besar maklumat pasaran semasa dan data dagangan sejarah, menapis dan mengkategorikan data dalam beberapa saat, membuat ramalan yang tepat dan memilih strategi dagangan yang paling sesuai.',
    },
    {
      'Key Translation': 'TrackMarketTrendsAndAnalyzeHistoryMarketData',
      English: 'Track Market Trends and Analyze History Market Data',
      'Chinese Simplified': '跟踪市场趋势并分析历史市场数据',
      'Chinese Traditional': '跟踪市場趨勢並分析歷史市場數據',
      Malay: 'Jejaki Aliran Pasaran dan Analisis Data Pasaran Sejarah',
    },
    {
      'Key Translation': 'ConductTechnicalAnalysisAndMakeTradingDecisions',
      English: 'Conduct Technical Analysis and Make Trading Decisions',
      'Chinese Simplified': '进行技术分析并做出交易决策',
      'Chinese Traditional': '進行技術分析並做出交易決策',
      Malay: 'Menjalankan Analisis Teknikal dan Membuat Keputusan Dagangan',
    },
    {
      'Key Translation': 'TrackInternationalNewsAndFinancialMarketInformation',
      English: 'Track International News and Financial Market Information',
      'Chinese Simplified': '跟踪国际新闻和金融市场信息',
      'Chinese Traditional': '跟踪國際新聞和金融市場信息',
      Malay: 'Jejaki Berita Antarabangsa dan Maklumat Pasaran Kewangan',
    },
    {
      'Key Translation': 'PredictAndExecuteBuyAndSellOrder',
      English: 'Predict and Execute Buy and Sell Order',
      'Chinese Simplified': '预测并执行买卖订单',
      'Chinese Traditional': '預測並執行買賣訂單',
      Malay: 'Ramalkan dan Laksanakan Pesanan Beli dan Jual',
    },
    {
      'Key Translation': 'TotalNewActiveMemberCurrentMonth',
      English: '<0>Total new active member</0></1>(current month)</1>',
      'Chinese Simplified': '<0>新活跃会员总数</0></1>（当月）</1>',
      'Chinese Traditional': '<0>新活躍會員總數</0></1>（當月）</1>',
      Malay: '<0>Jumlah ahli aktif baharu</0></1>(bulan semasa)</1>',
    },
    {
      'Key Translation': 'TotalGroupInvestmentCurrentMonth',
      English: '<0>Total group investment</0><1>(current month)</1>',
      'Chinese Simplified': '<0>团队总托管</0><1>（当月）</1>',
      'Chinese Traditional': '<0>團隊總託管</0><1>（當月）</1>',
      Malay: '<0>Jumlah pelaburan kumpulan</0><1>(bulan semasa)</1>',
    },
    {
      'Key Translation': 'PersonalInvestmentCurrentMonth',
      English: '<0>Personal Investment</0><1>(current month)</1>',
      'Chinese Simplified': '<0>个人托管</0><1>（当月）</1>',
      'Chinese Traditional': '<0>個人託管</0><1>（當月）</1>',
      Malay: '<0>Pelaburan Peribadi</0><1>(bulan semasa)</1>',
    },
  ];

  const en = {},
    zh = {},
    tw = {},
    hi = {},
    ja = {},
    ko = {},
    ms = {},
    th = {},
    vi = {};

  //  "Key Translation": "TotalMember",
  //  "English": "Total member",
  //  "Chinese Simplified": "会员总数",
  //  "Chinese Traditional": "會員總數",
  //  "Hindi": "कुल सदस्य ",
  //  "Japan": "会員総数",
  //  "Korean": "총 회원 수",
  //  "Malay": "Jumlah ahli",
  //  "Thai": "สมาชิกทั้งหมด",
  //  "Vietnamese": "Tổng số thành viên"

  data.forEach((item) => {
    en[item['Key Translation']] = item['English'];
    zh[item['Key Translation']] = item['Chinese Simplified'] || item['English'];
    tw[item['Key Translation']] =
      item['Chinese Traditional'] || item['English'];
    hi[item['Key Translation']] = item['Hindi'] || item['English'];
    ja[item['Key Translation']] = item['Japan'] || item['English'];
    ko[item['Key Translation']] = item['Korean'] || item['English'];
    ms[item['Key Translation']] = item['Malay'] || item['English'];
    th[item['Key Translation']] = item['Thai'] || item['English'];
    vi[item['Key Translation']] = item['Vietnamese'] || item['English'];
  });

  console.log(vi);

  const display = vi;
  return (
    <div>
      {Object.keys(display).map((keyTranslate) => {
        return (
          <div>
            "{keyTranslate}":{display[keyTranslate]}
          </div>
        );
      })}
    </div>
  );
}
